
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.imagine.world.dao.impl;


 import com.imagine.world.customdaosupport.CustomDAOSupport;
 import com.imagine.world.dao.ProductTagDAO;
 import com.imagine.world.models.ProductTag;
 import org.hibernate.Query;

 import java.io.Serializable;
 import java.util.List;
 
 
 /***************************************************
 *DAO class of PRODUCT_TAG table.
 *Generated on Wed Feb 05 18:09:02 ICT 2014
 ***************************************************/
 
 
 public class ProductTagDAOImpl extends CustomDAOSupport implements Serializable, ProductTagDAO {
 
 /**
 * @return Producttag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public List<ProductTag> findAll(){

		Query query = getDAOManager().createQuery(" select t from ProductTag t");

		List<ProductTag> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * Inserts Producttag
 * @param: ProductTag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public void save(ProductTag arg0){

		getDAOManager().persist(arg0);

	}
 
 /**
 * Updates Producttag
 * @param: ProductTag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public void update(ProductTag arg0){

		getDAOManager().merge(arg0);

	}
 
 /**
 * Removes Producttag
 * @param: ProductTag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public void delete(ProductTag arg0){

		getDAOManager().delete(arg0);

	}
 
 /**
 * @return Producttag
 * @param: java.lang.Integer IdProduct
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public List<ProductTag> getProductTagByIdProduct(Integer idProduct){

		Query query = getDAOManager().createQuery(" select t from ProductTag t where t.idProduct = ?1 ");

		query.setParameter(1, idProduct);


		List<ProductTag> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Producttag
 * @param: java.lang.Integer idProduct
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public List<ProductTag> getProductTagByIdProduct(Integer idProduct, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from ProductTag t where t.idProduct = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, idProduct);


		List<ProductTag> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Producttag
 * @param: java.lang.Integer IdTag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public List<ProductTag> getProductTagByIdTag(Integer idTag){

		Query query = getDAOManager().createQuery(" select t from ProductTag t where t.idTag = ?1 ");

		query.setParameter(1, idTag);


		List<ProductTag> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Producttag
 * @param: java.lang.Integer idTag
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Producttag
 */
	public List<ProductTag> getProductTagByIdTag(Integer idTag, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from ProductTag t where t.idTag = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, idTag);


		List<ProductTag> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 
 
 
 }