
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.imagine.world.dao;


 import com.imagine.world.models.Product;

 import java.io.Serializable;
 import java.util.Date;
 import java.util.List;
 
 
 /***************************************************
 *DAO interface of PRODUCT table.
 *Generated on Wed Feb 05 18:09:02 ICT 2014
 ***************************************************/
 
 
 public interface ProductDAO extends Serializable {
 
 /**
 * @return Product
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> findAll();
 
 /**
 * Inserts Product
 * @param: Product
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public void save(Product arg0);
 
 /**
 * Updates Product
 * @param: Product
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public void update(Product arg0);
 
 /**
 * Removes Product
 * @param: Product
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public void delete(Product arg0);
 
 /**
 * @return Product
 * @param: java.lang.Integer IdProduct
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByIdProduct(Integer idProduct);

/**
 * @return Product
 * @param: java.lang.Integer idProduct
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByIdProduct(Integer idProduct, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.lang.String Name
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByName(String name);

/**
 * @return Product
 * @param: java.lang.String name
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByName(String name, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.lang.String Description
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByDescription(String description);

/**
 * @return Product
 * @param: java.lang.String description
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByDescription(String description, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.lang.String Price
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByPrice(String price);

/**
 * @return Product
 * @param: java.lang.String price
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByPrice(String price, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.lang.String ProductCode
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByProductCode(String productCode);

/**
 * @return Product
 * @param: java.lang.String productCode
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByProductCode(String productCode, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.lang.Integer ProductAmount
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByProductAmount(Integer productAmount);

/**
 * @return Product
 * @param: java.lang.Integer productAmount
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByProductAmount(Integer productAmount, int startPosition, int maxResult);
 
 /**
 * @return Product
 * @param: java.util.Date LastUpdateDate
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByLastUpdateDate(Date lastUpdateDate);

/**
 * @return Product
 * @param: java.util.Date lastUpdateDate
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Product
 */
	public List<Product> getProductByLastUpdateDate(Date lastUpdateDate, int startPosition, int maxResult);

     /**
      *
      * @param productCode of course it is productCode
      *
      * @return
      */
    public int deleteByProductCode(String productCode);
 
 
 }