
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.imagine.world.dao;


 import com.imagine.world.models.Tag;

 import java.io.Serializable;
 import java.util.List;
 
 
 /***************************************************
 *DAO interface of TAG table.
 *Generated on Wed Feb 05 18:09:02 ICT 2014
 ***************************************************/
 
 
 public interface TagDAO extends Serializable {
 
 /**
 * @return Tag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> findAll();
 
 /**
 * Inserts Tag
 * @param: Tag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public void save(Tag arg0);
 
 /**
 * Updates Tag
 * @param: Tag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public void update(Tag arg0);
 
 /**
 * Removes Tag
 * @param: Tag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public void delete(Tag arg0);
 
 /**
 * @return Tag
 * @param: java.lang.Integer IdTag
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByIdTag(Integer idTag);

/**
 * @return Tag
 * @param: java.lang.Integer idTag
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByIdTag(Integer idTag, int startPosition, int maxResult);
 
 /**
 * @return Tag
 * @param: java.lang.String Name
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByName(String name);

/**
 * @return Tag
 * @param: java.lang.String name
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByName(String name, int startPosition, int maxResult);
 
 /**
 * @return Tag
 * @param: java.lang.String Description
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByDescription(String description);

/**
 * @return Tag
 * @param: java.lang.String description
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Wed Feb 05 18:09:02 ICT 2014
 * @See Tag
 */
	public List<Tag> getTagByDescription(String description, int startPosition, int maxResult);
 
 
 
 
 }